### ISSUE TITLE
MenuItem Support

### ISSUE THREAD

**Issue by toipi** [vape/Imui#1]
A pure C# ImGUI with a Canvas backend -- this is brilliant! Props on getting it this far.

I am looking to implement a menu with cascading submenus, like the MenuItems from Dear Imgui:
![Cascading MenuItems example](https://user-images.githubusercontent.com/1434736/42004842-00a624cc-7a72-11e8-8e5e-3789736e144e.gif)

Since you are familiar with the codebase, would you mind giving me a rough idea of how you would go about adding support for it?

**Comment by vape** [comment]
Hi @toipi, and thank you! 

I think the best place to start is to look at the `ImTree` control since it has similar behavior. For pane scaling, you could also look at how `ImButton` calculates its layout, and for drawing over the rest of the UI, see `ImPopup`. However, please note that I won't be accepting any feature requests for now because I'm still changing a lot of things and breaking a lot of APIs.

P.S. I have plans to implement menus too, so you can stick around for future versions :)

**Comment by toipi** [comment]
Thank you for the advice! I was able to hack together a very simple menu. It's nowhere near the quality of the built-in controls but it's enough for my use case.

https://github.com/user-attachments/assets/76161789-379e-44cb-bbb0-1c84f8f81eb5

Having delved deeper into the code I really can't get over how cool this project is. I'll be watching with excitement!

**Comment by toipi** [comment]
Oh my goodness, the menus in the latest demo are absolutely *beautiful*!
So clean!
